# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1cf17938e865a20f9419997ef1cede0796d8af72d862c3ea4bb0ca62837d61f87b8a0d54597c3d63bf1af056eba058501a13b27283beae95817aa8be42ec2a70

test:
  secret_key_base: e2225e597a34cf5930afcef41190303f025020f9ebf85ee1f2b98210c04aa735f98ad0186cde84e923d0ed1fee9feed342baf38f58c00c3bbae27204c927e435

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
